task_id: 8
type: MonoNavRearrangeOpenFridgeTask-v0
reward_measure: art_obj_reward
success_measure: art_obj_success
env_task_gym_id: "HabitatNavOpenFridgeTask"
task_spec_base_path: "skill_chain/pddl"
task_spec: "nav_open_fridge"
use_marker_options: ["fridge_push_point"]
update_measures:
  dataset:
    data_path: "data/datasets/replica_cad/rearrange/v1/{split}/in_fridge_1k_100.json.gz"
  task.measurements.mono_nav_to_obj_success: 
      must_call_stop: False
  # environment.iterator_options:
    # filter_criteria: ["art"]
  task.actions.arm_action:
    grip_controller: SuctionGraspAction
  task.measurements.art_obj_at_desired_state: 
    use_absolute_distance: False
  task.measurements.art_obj_reward:
    type: MonoArtObjReward
    wrong_grasp_end: True
    grasp_reward: 5.0
    marker_dist_reward: 1.0
    ee_dist_reward: 1.0
    # constraint_violate_pen: 1.0
  task:
    success_state: 1.2207963268
    use_marker_t: False
    success_reward: 10.0
    slack_reward: 0.0
max_episode_steps: 600
measures_list: 
  - "art_obj_success"
  - "art_obj_reward"
  - "art_obj_at_desired_state"
  - "ee_dist_to_marker"
  - "ee_to_object_distance.0"
  - "ee_to_rest_distance"
  - "force_terminate"
  - "reward"
  - "wrong_pick_marker_measure"
  - "did_pick_object"
  - "num_steps"